
(function(){function h(a){return"false"===a?!1:(a=a.match(/(http:|https:|)\/\/(player.|www.)?(vimeo\.com|youtu(be\.com|\.be|be\.googleapis\.com))\/(video\/|embed\/|watch\?v=|v\/)?([A-Za-z0-9._%-]*)(&\S+)?/))&&/youtu\.?be/g.test(a[3])?"youtube":a&&/vimeo/g.test(a[3])?"vimeo":!1}function k(a){return"false"===a?!1:(a=a.match(/(http:|https:|)\/\/(player.|www.)?(vimeo\.com|youtu(be\.com|\.be|be\.googleapis\.com))\/(video\/|embed\/|watch\?v=|v\/)?([A-Za-z0-9._%-]*)(&\S+)?/))?a[6]:!1}function l(a,d){var b=
new XMLHttpRequest;b.open("GET","https://vimeo.com/api/v2/video/"+a+".json",!0);b.onreadystatechange=function(){if(4===this.readyState&&200<=this.status&&400>this.status){var a=JSON.parse(this.responseText);d(a[0].thumbnail_large)}};b.send();b=null}var a,f,g="function"==typeof jQuery;g&&(a=jQuery);a?f=a("html").hasClass("is-builder"):f=document.querySelector("html").classList.contains("is-builder");var m=function(){var c={};return function(d){var b=a.Deferred();d in c?c[d]?b.resolve(c[d]):b.reject("Preview image not found."):
a("<img>").on("load",function(){if(120===(this.naturalWidth||this.width)){var a=this.src.split("/").pop();switch(a){case "maxresdefault.jpg":this.src=this.src.replace(a,"sddefault.jpg");break;case "sddefault.jpg":this.src=this.src.replace(a,"hqdefault.jpg");break;case "hqdefault.jpg":this.src=this.src.replace(a,"default.jpg");break;default:c[d]=null,b.reject("Preview image not found.")}}else b.resolve(c[d]=this.src)}).attr("src","https://img.youtube.com/vi/"+d+"/maxresdefault.jpg");return b}}();f&&
g&&(a.fn.outerFind=function(a){return this.find(a).addBack(a)},a(document).on("add.cards",function(c){if(a(c.target).hasClass("carousel")){var d=a("html").hasClass("desktop");a(c.target).outerFind("[data-bg-video-slide]").each(function(){var b=k(a(this).attr("data-bg-video-slide"));if(b){var c=a('<div class="mbr-background-video-preview"></div>').css({display:"none",backgroundSize:"cover",backgroundPosition:"center"});a(".container-slide",this).before(c);var f=h(a(this).attr("data-bg-video-slide")),
e=a(this).find(".mbr-overlay");"youtube"===f?(m(b).done(function(a){c.css("background-image",'url("'+a+'")').show()}),d&&a.fn.YTPlayer&&!a(this).find(".playerBox").length&&(a(".container-slide",this).before('<div class="mbr-background-video"></div>').prev().YTPlayer({videoURL:b,containment:"self",showControls:!1,mute:!0}),e.length&&a(".YTPOverlay",this).css({opacity:e.css("opacity"),backgroundColor:e.css("background-color")}),a(this).find(".image_wrapper img").css("opacity","0"),a(this).find(".image_wrapper .mbr-overlay").css("opacity",
"0"))):(l(b,function(a){c.css("background-image",'url("'+a+'")').show()}),d&&a.fn.vimeo_player&&!a(this).find(".playerBox").length&&(b=a(".container-slide",this).before('<div class="mbr-background-video"></div>').prev(),new Vimeo.Player(b),e.length&&a(".vimeo_player_overlay",this).css({opacity:e.css("opacity"),backgroundColor:e.css("background-color")})))}});a(c.target).find(".carousel-item iframe").css({transitionProperty:"opacity",transitionDuration:"1000ms"});a(this).on("slide.bs.carousel","section.carousel",
function(b){a(b.target).find(".carousel-item.active .mb_YTPlayer").each(function(){a(this).YTPPause()});a(b.target).find(".carousel-item.active .vimeo_player").each(function(){a(this).v_pause()});a(b.target).find(".carousel-item:not(.active) iframe").css("opacity",0)});a(this).on("slid.bs.carousel","section.carousel",function(b){a(b.target).find(".carousel-item.active .mb_YTPlayer").each(function(){a(this).YTPPlay()});a(b.target).find(".carousel-item.active .vimeo_player").each(function(){a(this).v_play()});
a(b.target).find(".carousel-item.active iframe").resize().css("opacity",1)})}}))})();
